Feature/two factor auth generator
Molinos/adminos pull request #4
Opened 2019-01-23 16:04 UTC by sawkas

2019-01-25 11:39 UTC, alsemyonov requested changes
А тут стоит добавить спеку, аналогичную этим: https://github.com/Molinos/adminos/blob/master/spec/lib/generators/adminos/

2019-01-30 09:34 UTC, alsemyonov commented
И ещё потребуется `git rebase` об `master`. Странно, я влил туда только твой предыдущий PR (про профиль), а этот теперь говорит про конфликты. Ты его разве не на профиле основывал?

2019-01-30 11:41 UTC, sawkas commented
> И ещё потребуется `git rebase` об `master`. Странно, я влил туда только твой предыдущий PR (про профиль), а этот теперь говорит про конфликты. Ты его разве не на профиле основывал?

ветвился от профиля

2019-01-30 11:41 UTC, sawkas commented
а, я потом еще фиксы в профиль делал

2019-01-30 11:57 UTC, alsemyonov commented
Да, это объясняет. 

Telegraphed from my Fridge

2019-02-04 11:02 UTC, alsemyonov commented
Moved to #11

2019-02-04 11:02 UTC, alsemyonov approved these changes

2019-02-04 11:02 UTC, alsemyonov commented
See #11

2019-02-04 11:02 UTC, closed without merging