i18n features
Molinos/adminos pull request #5
Opened 2019-01-25 09:50 UTC by sawkas

2019-01-25 11:38 UTC, alsemyonov requested changes
Надо бы ещё обновить спеку для генератора в связи с этими изменениями: https://github.com/Molinos/adminos/blob/master/spec/lib/generators/adminos/i18n_generator_spec.rb

2019-01-27 23:13 UTC, alsemyonov requested changes
А где, кстати, [`rails-i18n`](https://github.com/svenfuchs/rails-i18n)-то с переводами на русский и остальные языки? Я его, вроде, упоминал в задаче.

2019-01-27 23:15 UTC, alsemyonov commented on adminos.gemspec
> -  gem.add_dependency 'russian'
Надеюсь, [ключевые особенности](https://github.com/yaroslav/russian#%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B2%D1%8B%D0%B5-%D0%BE%D1%82%D0%BB%D0%B8%D1%87%D0%B8%D1%8F-%D0%BE%D1%82-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D0%BE%D0%B9-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8-i18n) ты прочёл и проверил, что без `russian`а ничего не сломалось.

2019-01-31 15:19 UTC, sawkas commented
> Надо бы ещё обновить спеку для генератора в связи с этими изменениями: https://github.com/Molinos/adminos/blob/master/spec/lib/generators/adminos/i18n_generator_spec.rb

добавил

2019-01-31 15:20 UTC, sawkas commented
> Надо бы ещё обновить спеку для генератора в связи с этими изменениями: https://github.com/Molinos/adminos/blob/master/spec/lib/generators/adminos/i18n_generator_spec.rb

Я же просто добавил гемы и генератор толка. Тесты в принципе актуальные.

2019-02-04 09:14 UTC, alsemyonov approved these changes

2019-02-04 09:14 UTC, merged