Feature/filters
Molinos/adminos pull request #6
Opened 2019-01-28 15:50 UTC by abuhtoyarov

For example

```ruby
class Admin::UsersController < Admin::BaseController
  add_filter :email
end
```

2019-01-30 09:48 UTC, alsemyonov requested changes
Пока не пробовал, как это выглядит, только читал код. Но к нему есть несколько вопросов (первый — самый важный)

2019-01-30 09:48 UTC, alsemyonov commented on adminos.gemspec
> +  gem.add_dependency 'ransack'
Зависимостями времени выполнения (runtime dependencies) объявлены сразу и `searchkick`, и `pg_search`.

То есть теперь чтобы использовать `adminos` нам нужно: 
1. обязательно поставить рядом ElasticSearch (даже если мы не собираемся использовать полнотекстовый поиск с его помощью), а так же
2. установить расширения PostgreSQL для:
    1. полнотекстового поиска, 
    2. триграмм, и
    3. двойного метафона.

Или `pg_search`у хватит чего-то одного?

Надо поменять на зависимости времени выполнения и сделать функции, зависящие от них условно-доступными (при наличии зависимости). Ну и добавить в какой-то генератор опцию на использование (и добавление в заисимости проекта) `searchkick` или `pg_search` для поиска.

2019-01-30 09:48 UTC, alsemyonov commented on lib/adminos/filters/forms.rb
> +          # binding.pry
🙀

2019-01-30 09:48 UTC, alsemyonov commented on lib/adminos/filters/forms.rb
> +          # TODO :numeric
А почему всё ещё `TODO`?

2019-01-30 10:53 UTC, abuhtoyarov commented on lib/adminos/filters/forms.rb
> +          # TODO :numeric
Пока подумал, что хватит обычной стоки, а если нет, то добавить по аналогии с датой, как диапазон. Но вообщем-то наверное стоит сразу сделать.

2019-01-30 12:01 UTC, alsemyonov commented
А, ещё описание PR тоже нужно добавить в `README.md`

2019-02-14 11:58 UTC, alsemyonov commented
@abuhtoyarov, тут поднакопилось замечаний и нужно ребейз сделать.

2019-02-15 09:13 UTC, abuhtoyarov commented
Можно чекать

2019-02-15 09:18 UTC, alsemyonov approved these changes

2019-02-15 09:18 UTC, merged