switch unicorn to puma with systemd
Molinos/adminos pull request #9
Opened 2019-01-30 11:38 UTC by sawkas

2019-01-30 11:51 UTC, alsemyonov requested changes
В целом почти всё хорошо, но есть _немножко вопросов и пара мелких исправлений_.

2019-01-30 11:51 UTC, alsemyonov commented on lib/adminos.rb
> +require 'awesome_nested_set'
Вот я всё же не уверен, что он прямо тут должен вызываться. И почему раньше без него работало? 

Давай позовём @abuhtoyarov на помощь, может быть он в курсе, почему без этой строки могло ломаться новое приложение? И как лучше исправить. Ведь у него и демка рабочая висит, и вообще он постоянно тестил разные фичи, и всё работало, ~но это не точно~.

2019-01-30 11:51 UTC, alsemyonov commented on lib/generators/adminos/install_generator.rb
> +      run 'bundle binstubs puma rspec-core # sidekiq'
`# sidekiq` —  это был комментарий)
А `rspec-core` ставится генератором CI.

2019-01-30 11:51 UTC, alsemyonov commented on lib/generators/templates/install/auto/config/environments/staging.rb
> +  config.assets.js_compressor = config.assets.js_compressor = Uglifier.new(harmony: true)
А это как связано с текущим PR? 🤔

2019-01-30 11:51 UTC, alsemyonov commented on lib/generators/templates/install/auto/config/deploy/staging.rb
> +set :user_home_dir, "/home/#{fetch(:user)}"
Знаешь, давай уберём вот эту переменную и заменим везде на значение.
Я сейчас не вижу большого смысла во введении дополнительной переменной, когда везде можно писать "/home/#{fetch(:user)}/..." и будет понятнее и очевиднее.

Я её, наверное, по-инерции забрал (или оставил), когда менял настройки на systemd.

2019-01-30 11:51 UTC, alsemyonov commented on lib/generators/templates/install/auto/config/deploy/staging.rb
> +set :nginx_sites_enabled_path, '/etc/nginx/conf.d'
Шаблон для Ubuntu можно было бы тоже добавить (закомментированным) — она как минимум не менее популярна для деплоя рельсов :)

2019-01-30 11:51 UTC, alsemyonov commented on lib/generators/templates/install/auto/lib/capistrano/tasks/setup_config.cap
> +  desc "Set up config fi"
Set up config fu~

2019-01-30 12:09 UTC, abuhtoyarov commented on lib/adminos.rb
> +require 'awesome_nested_set'
Вы не это ищете?

`adminos/lib/generators/templates/install/auto/config/initializers/awesome_nested_set.rb`

2019-01-30 12:18 UTC, sawkas commented on lib/generators/templates/install/auto/config/environments/staging.rb
> +  config.assets.js_compressor = config.assets.js_compressor = Uglifier.new(harmony: true)
без этого вебпакер не может собрать ассеты на стейдже, я тестил все в этом окружении и решил добавить

2019-01-30 12:22 UTC, sawkas commented on lib/generators/templates/install/auto/lib/capistrano/tasks/setup_config.cap
> +  desc "Set up config fi"
не понял

2019-01-30 12:40 UTC, alsemyonov commented on lib/adminos.rb
> +require 'awesome_nested_set'
Вот, точно, там же `rails generate admios:install` должен был создать инициализатор, который вызовет `awesome_nested_set`!

2019-01-30 12:41 UTC, alsemyonov commented on lib/generators/templates/install/auto/config/environments/staging.rb
> +  config.assets.js_compressor = config.assets.js_compressor = Uglifier.new(harmony: true)
Хороший поинт. Не относится, конечно, напрямую, но пусть остаётся, чтобы не заморачиваться с отдельным PRом

2019-01-31 14:07 UTC, alsemyonov approved these changes
👍

2019-01-31 14:08 UTC, merged